### ISSUE TITLE
明日のzutが見れるようにする

### ISSUE THREAD

**Issue by cocoeyes02** [ShuzoN/zut#18]
明日のzutが見れるようにするのがそもそも必要やな

_Originally posted by @cocoeyes02 in https://github.com/ShuzoN/zut/issues/17#issuecomment-781814720_

**Comment by ShuzoN** [comment]
![image](https://user-images.githubusercontent.com/5877377/111054078-d653f580-84ac-11eb-938d-f55b47894f3c.png)

**Comment by ShuzoN** [comment]
`--tomorrow` を含む場合明日の内容を出す形にする
