### ISSUE TITLE
indexから直接ロジックを呼び出さないようにする

### ISSUE THREAD

**Issue by IkezoeMakoto** [ShuzoN/zut#33]
できればparseした結果を元に、`help表示` `locationNameからの検索` `locationIdからの検索` のactionにルーティングする処理と処理した結果を表示ように整形するだけの処理に分離したい

イメージ
```
// indexから処理の実態を委譲される人
action.help()
action.searchByName()
action.searchById()
---
// 各ロジックで処理した内容の表示に責任を持つ人
presenter.help()
presenter.search()
```

_Originally posted by @IkezoeMakoto in https://github.com/ShuzoN/zut/pull/32#r612541009_

**Comment by ShuzoN** [comment]
argsをパースしてrouterがactionServiceに処理を移譲する感じにする

**Comment by ShuzoN** [comment]
終わってるのでclose
