### ISSUE TITLE
TSで型をいい感じにしたい

### ISSUE THREAD

**Issue by IkezoeMakoto** [ShuzoN/zut#34]
```
type ParseArgs  = {
  isHelp: boolean, 
  locationId: number, 
  locationName: string,  
  isTomorrow: boolean }
}
```

みたいな型が欲しくなるやつ...

_Originally posted by @ShuzoN in https://github.com/ShuzoN/zut/pull/32#r615365147_

**Comment by ShuzoN** [comment]
わかる。

**Comment by ShuzoN** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/aws-lambda

に対応したらok

**Comment by ShuzoN** [comment]
もうTypeScriptじゃね？

**Comment by ShuzoN** [comment]
あー、aws/lambdaの型定義使いたいって話かな

**Comment by cocoeyes02** [comment]
そういう話っぽいっすね〜

ちなみにこの辺って要ります？
https://github.com/ShuzoN/zut/blob/master/package.json#L8
https://github.com/ShuzoN/zut/blob/master/Makefile#L17

**Comment by ShuzoN** [comment]
いらないかなー

**Comment by cocoeyes02** [comment]
消しとくか〜対応しやす

**Comment by ShuzoN** [comment]
続きはhttps://github.com/ShuzoN/zut/issues/74でやるので close
