### ISSUE TITLE
tomorrowをtypoしているところがあるので直したい

### ISSUE THREAD

**Issue by cocoeyes02** [ShuzoN/zut#71]
tomorrow が tommorow になっている箇所があるので軒並み修正したい

ex.
https://github.com/ShuzoN/zut/blob/master/src/Types/zutool.ts#L25
https://github.com/ShuzoN/zut/blob/master/src/Actions/weatherAction.ts#L39

該当部分関連処理がテストコードで担保されていれば、grepで修正しても問題なさげ

**Comment by ShuzoN** [comment]
これタイポじゃなくて元々ずつーるから送られてくるレスポンスがそうなんですよね。なので仕様

**Comment by ShuzoN** [comment]
![Uploading image.png…]()

**Comment by ShuzoN** [comment]
<img width="494" alt="image" src="https://user-images.githubusercontent.com/5877377/166133332-e97707eb-eb2c-419f-8664-750e9c8ef987.png">

**Comment by ShuzoN** [comment]
@cocoeyes02

**Comment by cocoeyes02** [comment]
マジか〜とはいえコードを見ただけだとわからないのでコメントがあると嬉しい気持ちはある

とはいえ、対応不要だと思うのでcloseしやす！
